### ISSUE TITLE
Cijfers ophalen

### ISSUE THREAD

**Issue by Aap-Dev** [luxkatana/somtodayapi_python#1]
Weet iemand hoe je hier cijfers van een leerling mee kan laten zien?

**Comment by luxkatana** [comment]
> Weet iemand hoe je hier cijfers van een leerling mee kan laten zien?

Ik heb geen probleem hoor om het in de module te zetten als het mogelijk is

**Comment by luxkatana** [comment]
Ik moet nog echter dingen gaan updaten zoals andere features etcetera

**Comment by luxkatana** [comment]
> Weet iemand hoe je hier cijfers van een leerling mee kan laten zien?
Ik heb het kunnen plaatsen op dev branch, je kunt het echter proberen als je het wilt.

**Comment by luxkatana** [comment]
> Weet iemand hoe je hier cijfers van een leerling mee kan laten zien?

Ik ben vergeten om te zeggen maar ja lol nieuwe update met cijfers ophalen
